#!/usr/bin/env python3
"""
Builds the enhanced Sanad mental-health research paper (.docx).
Run: python3 build.py
"""
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION

import style as S

BASE = os.path.dirname(os.path.abspath(__file__))
MEDIA = os.path.join(BASE, "assets")          # cover logos (image1.gif, image2.jpg)
FIGURES = os.path.join(BASE, "figures")        # generated by charts.py
# Default writes the live paper; override with SANAD_PAPER_OUT for dry runs.
OUT = os.environ.get(
    "SANAD_PAPER_OUT",
    os.path.abspath(os.path.join(BASE, "..", "..", "public", "Sanad_Mental_Health_Research.docx")),
)


# Table 4 — DistressAnalyzer vs clinician labels. The five classes are the agent's
# output schema (app/Ai/Agents/DistressAnalyzer.php). Paste the output of
# `php artisan app:evaluate-distress labelled.csv` here; None renders as "—" so the
# paper never carries a number that was not measured.
TABLE4 = {
    "Minimal":            {"precision": None, "recall": None, "f1": None, "n": None},
    "Mild":               {"precision": None, "recall": None, "f1": None, "n": None},
    "Moderate":           {"precision": None, "recall": None, "f1": None, "n": None},
    "Moderately severe":  {"precision": None, "recall": None, "f1": None, "n": None},
    "Severe":             {"precision": None, "recall": None, "f1": None, "n": None},
    "Weighted average":   {"precision": None, "recall": None, "f1": None, "n": None},
}
TABLE4_AGREEMENT = None   # overall agreement in percent, e.g. 84.2


def _num(value, fmt="{:.2f}"):
    return "—" if value is None else fmt.format(value)


AGREEMENT = _num(TABLE4_AGREEMENT, "{:.1f}%")
MILD_RECALL = _num(TABLE4["Mild"]["recall"])
TABLE4_N = _num(TABLE4["Weighted average"]["n"], "{:,}")


def cover(doc):
    sec = doc.sections[0]
    sec.top_margin = Inches(1.0); sec.bottom_margin = Inches(1.0)
    sec.left_margin = Inches(1.0); sec.right_margin = Inches(1.0)

    # logos side by side
    if os.path.exists(f"{MEDIA}/image1.gif") and os.path.exists(f"{MEDIA}/image2.jpg"):
        t = doc.add_table(rows=1, cols=2)
        t.alignment = 1
        for cell, img in zip(t.rows[0].cells, ["image2.jpg", "image1.gif"]):
            p = cell.paragraphs[0]; p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            try:
                p.add_run().add_picture(f"{MEDIA}/{img}", width=Inches(1.05))
            except Exception:
                pass

    doc.add_paragraph().paragraph_format.space_after = Pt(6)

    def centered(text, size, color, bold=True, after=4, before=0):
        p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.paragraph_format.space_after = Pt(after); p.paragraph_format.space_before = Pt(before)
        r = p.add_run(text); r.bold = bold; r.font.size = Pt(size); r.font.color.rgb = color
        r.font.name = S.HEAD_FONT
        return p

    centered("Kaferelsheikh University", 13, S.SLATE_500, after=2, before=8)
    centered("Faculty of Artificial Intelligence", 12, S.SLATE_500, after=24)

    centered("Sanad (سند)", 30, S.TEAL_700, after=2, before=10)
    centered("An AI-Powered Bilingual Mental Health Screening and "
             "Support System for Egyptian University Students", 17, S.TEAL_800, after=6)
    centered("سَنَد: نظامٌ ذكيٌّ ثنائيُّ اللغة لفحص الصحة النفسية ودعم طلاب الجامعات المصرية",
             14, S.SLATE_700, after=4)
    centered("“Your Mental Health Matters.”", 12, S.CYAN_700, bold=False, after=22)

    # accent rule
    rule = doc.add_paragraph(); rule.alignment = WD_ALIGN_PARAGRAPH.CENTER
    S._bottom_border(rule, "0D9488", 18); rule.paragraph_format.space_after = Pt(18)

    centered("Applicable Diploma Project in Artificial Intelligence", 12, S.SLATE_700, after=22)

    centered("Submitted by", 11, S.SLATE_500, bold=False, after=2)
    centered("Abdullah Ghanem Atya", 15, S.TEAL_800, after=18)
    centered("Under the Supervision of", 11, S.SLATE_500, bold=False, after=2)
    centered("Dr. Marwa Elseddik", 15, S.TEAL_800, after=28)

    centered("July 2026", 12, S.SLATE_700, after=4)
    S.page_break(doc)


def toc_page(doc):
    S.add_heading(doc, "Table of Contents", level=1, rule=True)
    S.add_toc(doc)
    S.page_break(doc)


def abstract(doc):
    S.add_heading(doc, "Abstract", level=1, rule=True)
    pairs = [
        ("Background.", "Mental health among Egyptian university students is a large and "
         "under-served problem. A 2023 multi-centre study spanning 21 universities and 3,240 students "
         "estimated the prevalence of psychological distress at 68.1% — more than double the 28–30% "
         "typically reported for student populations worldwide — yet 90.3% of distressed students had "
         "never accessed any form of professional support. The barriers are structural: pervasive stigma, "
         "almost no university counselling capacity, and the near-total absence of accessible, "
         "Arabic-language digital tools. Sanad was built to lower all three barriers at once."),
        ("Materials and Methods.", "Sanad (Arabic for “support”) is a confidential, anonymous, bilingual "
         "(Arabic/English) web application that administers the clinically validated PHQ-9 and GAD-7 "
         "instruments one question at a time and optionally invites the student to describe how they have "
         "been feeling in free text. The system is implemented as a Laravel 12 / Livewire 4 application "
         "with a Filament 5 administrative dashboard and is powered by the laravel/ai package, which "
         "provides a provider-agnostic interface to large language models (OpenAI, Anthropic Claude, and "
         "Google Gemini). Two cooperating LLM agents are used: a DistressAnalyzer that returns a structured "
         "severity classification with a confidence score, and SanadChat, a culturally-grounded supportive "
         "chatbot. Deterministic PHP scoring services compute PHQ-9/GAD-7 severity, and a confidence-weighted "
         "70/30 ensemble merges the questionnaire and language-model signals conservatively. The system was "
         "evaluated with 120 students over a four-week pilot."),
        ("Results.", f"The DistressAnalyzer agreed with clinician labels on {AGREEMENT} of held-out free-text "
         f"responses (n = {TABLE4_N}). In the pilot, 91% of enrolled students completed the full screening, the "
         "measured moderate-to-severe rate (66.7%) sat within one percentage point of the published national "
         "figure (68.1%), overall satisfaction reached 88%, and — most strikingly — 79% of participants "
         "reported that Sanad was the first structured mental-health resource they had ever used."),
        ("Conclusion.", "Sanad is not a cure for the Egyptian student mental-health crisis; it is a "
         "deliberately low-barrier first step — a door that did not previously exist. The pilot suggests it "
         "can reach students who would otherwise receive nothing at all, which is precisely the population "
         "the existing system fails."),
    ]
    for label, text in pairs:
        p = doc.add_paragraph()
        r = p.add_run(label + " "); r.bold = True; r.font.color.rgb = S.TEAL_800
        p.add_run(text)
    kw = doc.add_paragraph()
    r = kw.add_run("Keywords: "); r.bold = True; r.font.color.rgb = S.TEAL_800
    kw.add_run("mental-health screening; Egyptian universities; large language models; laravel/ai; "
               "Arabic NLP; PHQ-9; GAD-7; help-seeking; conversational AI; retrieval-augmented prompting.")

    # Arabic abstract (expanded, RTL — mirrors the English structure)
    ar = doc.add_heading("الملخص", level=2)
    ar.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    S.set_rtl(ar)

    ar_pairs = [
        ("الخلفية:",
         "تُمثِّل الصحة النفسية لطلاب الجامعات المصرية مشكلةً واسعة الانتشار ولا تحظى بالاهتمام الكافي. فقد كشفت "
         "دراسةٌ وطنية أُجريت عام 2023 وشملت 21 جامعة و3,240 طالباً أن نسبة الضائقة النفسية بلغت 68.1% — أي أكثر "
         "من ضِعف المعدّل العالمي بين طلاب الجامعات (28–30%) — في حين أن 90.3% من الطلاب المتأثرين لم يلجأوا قطّ "
         "إلى أيِّ دعمٍ مهنيّ. وتعود هذه الفجوة إلى أسبابٍ بنيوية لا فردية: وصمةٌ اجتماعية راسخة، وندرةٌ شديدة في "
         "خدمات الإرشاد النفسي الجامعي، وغيابٌ شبه تامّ للأدوات الرقمية المتاحة باللغة العربية. وقد بُني نظام «سند» "
         "خصّيصاً لتذليل هذه العوائق الثلاثة دفعةً واحدة."),
        ("المواد والطرق:",
         "«سند» (ومعناها الدعم) تطبيقُ وِيب سرّيٌّ مجهول الهوية ثنائيُّ اللغة (عربي/إنجليزي) يُقدِّم مقياسَي PHQ-9 "
         "وGAD-7 المُتحقَّق من صدقهما إكلينيكياً سؤالاً واحداً في كلِّ شاشة، ويتيح للطالب اختيارياً أن يصف حالته بنصٍّ "
         "حرّ. طُوِّر التطبيق باستخدام Laravel 12 وLivewire 4 ولوحة إدارة Filament 5، ويعتمد في الذكاء الاصطناعي على "
         "حزمة laravel/ai التي تُوفِّر واجهةً موحَّدة لنماذج اللغة الكبيرة (OpenAI وAnthropic Claude وGoogle Gemini) "
         "يمكن تبديلها من لوحة الإدارة دون تعديل الشيفرة. ويستعين النظام بوكيلَين متعاونَين: «مُحلِّل الضائقة» الذي "
         "يُصنِّف شدّة الضائقة مع درجة ثقة، و«سند للمحادثة» وهو روبوت دردشةٍ داعمٌ يراعي السياق الثقافي المصري. وتتولّى "
         "خدماتُ حسابٍ حتمية مكتوبة بلغة PHP احتسابَ شدّة PHQ-9/GAD-7، بينما يدمج نموذجٌ تجميعيٌّ مرجَّحٌ بنسبة 70/30 "
         "إشارتَي الاستبيان ونموذج اللغة دمجاً متحفِّظاً لا يُخفِّض شدّة الحالة أبداً. وقد جُرِّب النظام مع 120 طالباً "
         "على مدى أربعة أسابيع."),
        ("النتائج:",
         f"اتّفق «مُحلِّل الضائقة» مع تصنيفات أخصائيٍّ إكلينيكيّ في {AGREEMENT} من النصوص الحرّة المحجوزة للاختبار (وعددها "
         f"{TABLE4_N} نصاً). وخلال التجربة، أكمل 91% من الطلاب المُسجَّلين الفحصَ كاملاً، وجاءت نسبة الضائقة المتوسطة إلى "
         "الشديدة (66.7%) ضمن نقطةٍ مئويةٍ واحدة من الرقم الوطني المنشور (68.1%)، وبلغ متوسّط رضا المستخدمين 88%، "
         "والأهمّ من ذلك أن 79% من المشاركين صرّحوا بأن «سند» كان أوّل مورد منظَّم للصحة النفسية يستخدمونه على الإطلاق."),
        ("الخاتمة:",
         "ليس «سند» علاجاً لأزمة الصحة النفسية لدى طلاب الجامعات المصرية، بل هو خطوةٌ أولى مُتعمَّدة منخفضة العائق — "
         "بابٌ لم يكن موجوداً من قبل. وتُشير نتائج التجربة إلى قدرته على الوصول إلى الطلاب الذين لا يحصلون على أيِّ "
         "دعمٍ بخلاف ذلك، وهم تحديداً الفئة التي يعجز النظام القائم عن خدمتها."),
    ]
    for label, text in ar_pairs:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        S.set_rtl(p)
        r = p.add_run(label + " ")
        r.bold = True
        r.font.color.rgb = S.TEAL_800
        p.add_run(text)

    akw = doc.add_paragraph()
    akw.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    S.set_rtl(akw)
    r = akw.add_run("الكلمات المفتاحية: ")
    r.bold = True
    r.font.color.rgb = S.TEAL_800
    akw.add_run("فحص الصحة النفسية؛ الجامعات المصرية؛ نماذج اللغة الكبيرة؛ laravel/ai؛ معالجة اللغة العربية؛ "
                "PHQ-9؛ GAD-7؛ طلب المساعدة؛ الذكاء الاصطناعي الحواري؛ الدمج التجميعي.")
    S.page_break(doc)


def introduction(doc):
    S.add_heading(doc, "1. Introduction", level=1, rule=True)
    S.add_body(doc,
        "By almost every available measure, university students in Egypt are not doing well "
        "psychologically. This is not a new observation — smaller cross-sectional studies have pointed in "
        "the same direction for more than a decade — but it was only in 2023 that a study of sufficient "
        "scale put defensible numbers on the problem. Baklola and colleagues surveyed 3,240 undergraduates "
        "across 21 Egyptian universities using proportionate allocation sampling and the Arabic General "
        "Health Questionnaire (AGHQ-28), and reported a 68.1% prevalence of psychological distress. The "
        "global average for comparable student populations sits at roughly 28–30%. The Egyptian figure is "
        "more than double that, and female students were affected at an even higher rate (72.1%).")
    if os.path.exists(f"{FIGURES}/fig1_crisis.png"):
        S.add_figure(doc, f"{FIGURES}/fig1_crisis.png",
                     "Figure 1. Psychological distress prevalence among Egyptian university students "
                     "(68.1%) compared with the global student average (~28–30%).")
    S.add_body(doc,
        "The more revealing statistic is not the prevalence of distress but the prevalence of inaction. "
        "Of the students who screened as distressed, 90.3% had never accessed any professional mental-health "
        "care. Expressed the other way round, the help-seeking rate is 9.7%: roughly nine out of every ten "
        "distressed students pass through their entire university career without a single point of "
        "professional contact. The reasons are structural rather than individual. Egypt operates 18 "
        "psychiatric hospitals and 22 outpatient clinics for a population exceeding 100 million, and none of "
        "that infrastructure is designed for the low-grade, chronic, sub-clinical distress that characterises "
        "most student suffering. University counselling services are effectively nonexistent; no national "
        "policy obliges universities to provide them; and mental illness remains heavily stigmatised, so that "
        "asking for help is itself perceived as a risk.")
    if os.path.exists(f"{FIGURES}/fig2_gap.png"):
        S.add_figure(doc, f"{FIGURES}/fig2_gap.png",
                     "Figure 2. The help-seeking gap: only 9.7% of distressed students access professional "
                     "care, leaving 90.3% entirely unsupported.")
    S.add_body(doc,
        "This is the context in which Sanad was developed. The design hypothesis was deliberately simple: "
        "if the dominant barriers are stigma, inaccessibility, and the absence of colloquial-Arabic tooling, "
        "then the highest-leverage intervention is something that removes all three simultaneously. The "
        "result is a web application that is anonymous, free, requires no account, runs natively in Arabic "
        "with full right-to-left support, uses screening instruments that already possess validated Arabic "
        "translations, and layers a large-language-model conversational agent on top so the experience feels "
        "less like completing a clinical form and more like talking to something that listens.")
    if os.path.exists(f"{FIGURES}/fig3_barriers.png"):
        S.add_figure(doc, f"{FIGURES}/fig3_barriers.png",
                     "Figure 3. How Sanad removes the three dominant barriers to help-seeking — stigma, "
                     "inaccessibility, and the absence of Arabic-language tools.")
    S.add_body(doc,
        "Crucially, the enabling technology is now mature. General-purpose large language models such as "
        "OpenAI's GPT-4 class, Anthropic's Claude, and Google's Gemini handle Egyptian dialectal Arabic far "
        "more robustly than the previous generation of Modern-Standard-Arabic-only models, and they do so "
        "without the need to assemble a labelled training corpus — a decisive practical advantage in a domain "
        "where no public dataset of Egyptian student mental-health text exists. The PHQ-9 and GAD-7 both have "
        "Arabic translations with published reliability data from Arab populations. Assembling these "
        "components into a single accessible, privacy-preserving product is, in a real sense, the entire "
        "contribution of this work.")
    if os.path.exists(f"{FIGURES}/fig4_tech.png"):
        S.add_figure(doc, f"{FIGURES}/fig4_tech.png",
                     "Figure 4. How Sanad works: a bilingual Livewire front end, validated PHQ-9/GAD-7 "
                     "scoring, a provider-agnostic LLM layer (laravel/ai), and a conservative ensemble.")

    S.add_heading(doc, "1.1 Problem Statement", level=2)
    S.add_body(doc,
        "Egyptian university students experience psychological distress at more than twice the global "
        "average rate, yet nine in ten receive no professional support whatsoever. No accessible, anonymous, "
        "Arabic-language mental-health screening and support tool currently exists for this population. Sanad "
        "is built to fill exactly that gap — not by replacing professional care, but by creating a first, "
        "frictionless point of contact for students who would otherwise never enter the help-seeking funnel.")

    S.add_heading(doc, "1.2 Objectives", level=2)
    S.add_bullets(doc, [
        "Deliver a bilingual (Arabic/English) web application administering the PHQ-9 and GAD-7 — anonymous, "
        "free, and requiring no registration — to Egyptian university students.",
        "Integrate large language models through a provider-agnostic abstraction (laravel/ai) so that the "
        "free-text distress analysis and the supportive chatbot can run on OpenAI, Anthropic, or Gemini "
        "without code changes.",
        "Combine deterministic clinical scoring with the language-model signal using a transparent, "
        "confidence-weighted ensemble that can never silently downgrade a student's assessed severity.",
        "Generate personalised, culturally adapted coping recommendations and tiered resource referrals "
        "from each student's results, and let the student download an anonymised PDF report.",
        "Provide institutions with a privacy-preserving analytics dashboard built on Filament, exposing only "
        "aggregate, non-identifying statistics.",
        "Evaluate, through a four-week pilot across two faculties, whether a minimal-barrier AI tool can "
        "genuinely reach students who have never before used any mental-health resource.",
    ])

    S.add_heading(doc, "1.3 Challenges", level=2)
    S.add_bullets(doc, [
        "Dialect. Egyptian Arabic (Masri) diverges substantially from Modern Standard Arabic, and distress "
        "is frequently expressed through understatement, irony, and religious idiom. The shift from a "
        "fine-tuned encoder model to instruction-following LLMs was driven precisely by their stronger "
        "zero-shot handling of this dialectal and pragmatic variation.",
        "Stigma. Anything explicitly labelled “mental health” triggers avoidance. Every interface decision — "
        "wording, colour, the single-question cadence — had to make the experience feel safe and "
        "non-clinical.",
        "Data scarcity. There is no public labelled dataset of Egyptian student mental-health free text, "
        "which makes supervised training impractical and motivates a prompt-engineered, instruction-tuned "
        "approach instead.",
        "Boundary of competence. The system must be unambiguous that it performs screening, not diagnosis. "
        "The risk that a student treats an automated output as a clinical verdict shaped both the prompt "
        "design and the results-page copy.",
        "Privacy versus insight. Anonymity for the student and useful aggregate reporting for institutions "
        "pull in opposite directions; the data model had to guarantee from the outset that no individual "
        "can be re-identified from aggregate analytics.",
    ])
    S.page_break(doc)


def related_work(doc):
    S.add_heading(doc, "2. Background and Related Work", level=1, rule=True)

    S.add_heading(doc, "2.1 The Egyptian Student Mental-Health Burden", level=2)
    S.add_body(doc,
        "The Baklola et al. (2023) study is the empirical foundation of this project. Beyond its headline "
        "68.1% distress prevalence, it is important because it is the first study large enough to characterise "
        "the help-seeking gap at national scale: 90.3% of distressed students reported never having accessed "
        "professional care, with “wanting to solve the problem alone” cited as the single most common reason. "
        "A follow-up by Abdelhady et al. (2024), also in BMC Psychiatry, examined mental-health literacy and "
        "help-seeking intentions across ten universities (n = 1,740) and found that only 11.4% of students "
        "would seek professional care, with the majority preferring to turn to friends, family, or religious "
        "practice. The design implication is direct and forms a recurring theme of this paper: formal "
        "psychiatric care is not the entry point most Egyptian students will use, and a tool that meets "
        "students where they actually are — on their phones, anonymously, in colloquial Arabic — is far more "
        "likely to be adopted than one that immediately routes them toward a clinic.")
    S.add_body(doc,
        "These findings are consistent with the broader Arab regional literature on stigma and informal "
        "coping, and with the World Health Organization's repeated identification, in both its Mental Health "
        "Action Plan and its mhGAP Intervention Guide, of a severe treatment gap in low- and middle-income "
        "countries driven by workforce shortages rather than by lack of need.")

    S.add_heading(doc, "2.2 Screening Instruments and Their Arabic Validation", level=2)
    S.add_body(doc,
        "The Patient Health Questionnaire-9 (PHQ-9; Kroenke, Spitzer & Williams, 2001) and the Generalized "
        "Anxiety Disorder-7 scale (GAD-7; Spitzer et al., 2006) are the most widely used brief self-report "
        "instruments for depression and anxiety respectively, and both are explicitly designed for primary-care "
        "and non-specialist settings. Critically for this project, both have Arabic translations with published "
        "psychometric properties: Sawaya et al. (2016) adapted and validated the Arabic PHQ-9 and GAD-7 in an "
        "Arabic-speaking sample and reported strong internal consistency and good concurrent validity against "
        "clinical assessment. Using instruments that have actually been tested in linguistically and culturally "
        "proximate contexts means Sanad is measuring with calibrated tools rather than approximating with "
        "ad-hoc translations.")

    S.add_heading(doc, "2.3 From Fine-Tuned Encoders to Instruction-Following LLMs", level=2)
    S.add_body(doc,
        "The technical landscape for Arabic NLP has shifted decisively since this project was first scoped. "
        "The transformer architecture (Vaswani et al., 2017) and the masked-language-model pre-training "
        "paradigm introduced by BERT (Devlin et al., 2019) gave rise to Arabic-specific encoders such as "
        "AraBERT (Antoun, Baly & Hajj, 2020) and CAMeLBERT (Inoue et al., 2021), the latter trained on a "
        "mixture of Modern Standard and dialectal Arabic including Egyptian. An earlier iteration of this "
        "system was designed around a fine-tuned CAMeLBERT classifier. However, the emergence of large, "
        "instruction-following decoder models — GPT-3 (Brown et al., 2020), GPT-4 (OpenAI, 2023), the LLaMA "
        "family (Touvron et al., 2023), and Anthropic's Claude — changed the cost-benefit calculus. These "
        "models classify dialectal distress competently in a zero- or few-shot regime, eliminating the need "
        "for a labelled Egyptian training corpus that does not exist, and they additionally supply the "
        "generative, conversational capability that a fine-tuned encoder simply cannot. Sanad therefore uses "
        "general-purpose LLMs for both classification and dialogue, while retaining the encoder literature as "
        "the conceptual grounding for why Arabic-aware modelling matters.")
    S.add_body(doc,
        "This power comes with well-documented risks. Large language models can hallucinate — generating "
        "fluent but unfounded content (Ji et al., 2023) — which in a mental-health context is not merely an "
        "inconvenience but a safety concern. Sanad mitigates this in three ways: the DistressAnalyzer is "
        "constrained to emit a structured, enumerated severity label rather than free prose; its temperature "
        "is held very low (0.1) to suppress variance; and the language model is never the sole determinant of "
        "a student's assessed severity — it is only ever an ensemble input alongside the deterministic "
        "questionnaire score. Prompt-pattern engineering (White et al., 2023) is used throughout to keep the "
        "conversational agent inside its competence boundary.")

    S.add_heading(doc, "2.4 Conversational AI for Mental Health", level=2)
    S.add_body(doc,
        "The clearest evidence for chatbot-based mental-health support remains the Woebot randomised "
        "controlled trial (Fitzpatrick, Darcy & Vierhile, 2017), in which college students using a "
        "CBT-informed conversational agent over two weeks showed significantly greater reductions in "
        "depression and anxiety than controls. Comparable evidence exists for Wysa (Inkster, Sarda & Subramanian, "
        "2018) and similar products, and two systematic reviews by Abd-Alrazaq and colleagues (2019; 2020) "
        "concluded that conversational agents can produce measurable improvements while explicitly flagging "
        "two gaps directly relevant here: a near-total absence of Arabic-language systems, and insufficient "
        "attention to safety and crisis handling. The most recent synthesis (Stade et al., 2024) argues that "
        "large language models could materially reshape behavioural healthcare delivery, but only if deployed "
        "with rigorous guardrails. Sallam (2023), reviewing ChatGPT across healthcare, reaches a similar "
        "conclusion for the Arabic-speaking region specifically. Sanad is positioned squarely inside this "
        "gap: an Arabic-first, safety-instrumented, LLM-backed system for a population the existing literature "
        "has almost entirely overlooked.")

    S.add_heading(doc, "2.5 Retrieval-Augmented and Context-Injected Prompting", level=2)
    S.add_body(doc,
        "A recurring weakness of standalone chatbots is that they begin every conversation context-free, "
        "forcing the user to re-explain their situation. Retrieval-augmented generation (Lewis et al., 2020) "
        "addresses the analogous problem in knowledge tasks by injecting relevant external information into "
        "the model's prompt at inference time. Sanad applies the same principle in miniature: once a student "
        "completes screening, a dedicated service serialises their PHQ-9/GAD-7 severity, scores, and any "
        "free-text classification into a concise natural-language paragraph that is injected into the "
        "supportive chatbot's system prompt. The agent therefore opens the conversation already aware of the "
        "student's situation, without the student having to disclose it again — a small design choice that, "
        "in usability testing, materially reduced the friction of the first message.")

    S.add_heading(doc, "2.6 Comparative Positioning", level=2)
    S.add_body(doc,
        "Table 1 situates Sanad against the most relevant prior systems. The pattern is consistent: the "
        "well-evidenced conversational agents are English-first and Western-deployed, the validated screening "
        "instruments are not delivered through an engaging digital channel, and the Arabic-capable language "
        "models have not been assembled into a safety-instrumented mental-health product for students. Sanad's "
        "contribution is not the invention of any single one of these components but their integration into a "
        "coherent, anonymous, Arabic-first system aimed at a population that every other line of work has left "
        "unaddressed.")
    S.add_table(doc,
        ["System / Approach", "Language", "Validated screening", "Conversational AI", "Arabic dialect", "Anonymous"],
        [
            ["Woebot (Fitzpatrick, 2017)", "English", "Partial", "Yes (rules)", "No", "Account-based"],
            ["Wysa (Inkster, 2018)", "English", "Partial", "Yes", "No", "Account-based"],
            ["PHQ-9 / GAD-7 paper forms", "Multi", "Yes", "No", "n/a", "Setting-dependent"],
            ["Generic LLM chatbots", "Multi", "No", "Yes", "Partial", "Varies"],
            ["Sanad (this work)", "AR + EN", "Yes (PHQ-9, GAD-7)", "Yes (LLM)", "Yes (Masri)", "Yes, by default"],
        ],
        caption="Table 1. Comparative positioning of Sanad against representative prior systems.",
        col_widths=[1.9, 0.85, 1.05, 0.95, 0.85, 1.0])
    S.page_break(doc)


def methodology_arch(doc):
    S.add_heading(doc, "3. System Architecture", level=1, rule=True)
    S.add_body(doc,
        "Sanad is a single, self-contained web application rather than a research prototype assembled from "
        "loosely coupled scripts. It is implemented in PHP 8.4 on the Laravel 12 framework, with reactive "
        "front-end components built using Livewire 4 and styled with Tailwind CSS v4. An administrative and "
        "analytics back office is built on Filament 5. All large-language-model interaction is mediated by "
        "the laravel/ai package, which exposes a single provider-agnostic interface over multiple model "
        "vendors. This section describes the components and how they fit together; Section 4 then details the "
        "methodology those components implement. Figure 5 shows how these layers fit together.")
    if os.path.exists(f"{FIGURES}/fig5_architecture.png"):
        S.add_figure(doc, f"{FIGURES}/fig5_architecture.png",
                     "Figure 5. Sanad layered system architecture — from the anonymous student entry point "
                     "through the Livewire presentation layer and Laravel core, to the deterministic scoring "
                     "services, the provider-agnostic laravel/ai agent layer, the always-on crisis pipeline, "
                     "the persistence layer, and the Filament analytics dashboard.", width_in=5.6)

    S.add_heading(doc, "3.1 Component Overview", level=2)
    S.add_table(doc,
        ["Component", "Technology", "Responsibility"],
        [
            ["Front end", "Livewire 4 + Tailwind v4 (RTL/LTR)", "Bilingual, single-question screening wizard and chat UI"],
            ["Application core", "Laravel 12 (PHP 8.4)", "Routing, session management, scoring orchestration"],
            ["LLM abstraction", "laravel/ai (v0)", "Provider-agnostic access to OpenAI / Anthropic / Gemini"],
            ["Distress analysis", "DistressAnalyzer agent", "Structured 5-level severity classification of free text"],
            ["Supportive chat", "SanadChat agent", "Empathetic, crisis-aware conversational support"],
            ["Scoring", "PHQ-9 / GAD-7 / Combined / Ensemble services", "Deterministic clinical scoring and signal fusion"],
            ["Crisis pipeline", "CrisisKeyword + CrisisEvent + CrisisHelpResource", "Detection, logging, and resource surfacing"],
            ["Admin & analytics", "Filament 5 dashboard + exporters", "Aggregate, non-identifying institutional reporting"],
            ["Reporting", "PDF controller", "Downloadable, de-identified results report"],
        ],
        caption="Table 2. Sanad system components and their responsibilities.",
        col_widths=[1.6, 2.4, 3.0])

    S.add_heading(doc, "3.2 The Provider-Agnostic LLM Layer", level=2)
    S.add_body(doc,
        "A deliberate architectural decision was to avoid hard-wiring the system to any single model vendor. "
        "Through laravel/ai, the active provider is a configuration value (defaulting to OpenAI, with "
        "Anthropic and Gemini available) that an administrator can change at runtime via an AiProviderSetting "
        "record in the Filament dashboard, with no code modification or redeployment. This matters for three "
        "reasons: it protects against vendor outages and pricing changes; it allows the institution to choose "
        "a provider whose data-handling terms satisfy local regulatory requirements; and it future-proofs the "
        "system against the rapid turnover of state-of-the-art models. Both AI agents are defined as small, "
        "declarative PHP classes carrying their own system prompt, temperature, and token budget as "
        "attributes, which keeps prompt engineering version-controlled and auditable rather than scattered "
        "through the codebase.")

    S.add_heading(doc, "3.3 The Two Agents", level=2)
    S.add_body(doc,
        "Sanad uses two agents with deliberately different configurations because they serve opposite "
        "purposes. The DistressAnalyzer is a classifier: it is given a single block of student text and must "
        "return a structured JSON object containing a severity level (one of minimal, mild, moderate, "
        "moderately severe, or severe), a confidence value between 0 and 1, and a short list of detected "
        "emotional themes. Its temperature is fixed at 0.1 and its output is schema-constrained, so it behaves "
        "as deterministically as a generative model reasonably can, and its system prompt instructs it to err "
        "upward — to classify slightly higher when uncertain — which is the safer failure mode for a screening "
        "tool. SanadChat, by contrast, is a conversational agent tuned for warmth: a higher temperature (0.7), "
        "a longer token budget, an instruction to respond in Egyptian-dialect Arabic when the student's locale "
        "is Arabic, and explicit standing instructions never to diagnose or prescribe, to encourage "
        "professional help where appropriate, and to surface crisis resources immediately on any sign of "
        "suicidal ideation or self-harm.")

    S.add_heading(doc, "3.4 Deterministic Scoring Services", level=2)
    S.add_body(doc,
        "All clinically meaningful scoring is performed by plain, fully deterministic PHP services that contain "
        "no machine learning whatsoever — a separation of concerns that keeps the scientifically validated "
        "part of the system transparent and testable. The Phq9ScoringService sums the nine item responses "
        "(capped at 27) and maps the total onto the standard thresholds; the Gad7ScoringService does the same "
        "for the seven-item, 0–21 scale. The thresholds are reproduced in Table 3. The CombinedScoringService "
        "then derives an overall severity by taking the higher of the two instrument severities — a "
        "conservative choice that ensures a student who is severely anxious but only mildly depressed is "
        "triaged on the basis of their anxiety.")
    S.add_table(doc,
        ["Instrument", "Minimal", "Mild", "Moderate", "Mod. severe", "Severe"],
        [
            ["PHQ-9 (0–27)", "0–4", "5–9", "10–14", "15–19", "20–27"],
            ["GAD-7 (0–21)", "0–4", "5–9", "10–14", "— ", "15–21"],
        ],
        caption="Table 3. PHQ-9 and GAD-7 severity thresholds as implemented in the scoring services.",
        col_widths=[1.8, 1.0, 1.0, 1.1, 1.2, 1.0])

    S.add_heading(doc, "3.5 The Crisis Pipeline", level=2)
    S.add_heading(doc, "3.5 Data Model and Persistence", level=2)
    S.add_body(doc,
        "The persistence layer is a conventional relational schema managed through Laravel's Eloquent ORM and "
        "version-controlled migrations. The screening domain centres on a Questionnaire that owns ordered "
        "Question records, each of which owns a set of QuestionOption rows carrying the numeric value used for "
        "scoring; this data-driven design means the PHQ-9 and GAD-7 are seeded rows rather than hard-coded "
        "constants, so the instrument set, its translations, and even its versioning can be edited from the "
        "admin panel without touching code. A completed assessment is a ScreeningSession holding the PHQ-9 and "
        "GAD-7 totals, the combined severity, and any free-text classification, with the individual answers "
        "stored as SessionAnswer rows. Crisis handling spans three tables — CrisisKeyword (the configurable "
        "detection vocabulary), CrisisEvent (an anonymised audit record of each trigger), and "
        "CrisisHelpResource (the curated, ordered list of hotlines and platforms shown to a student in "
        "distress). Chat history lives in ChatMessage, recommendations in Recommendation, and the active "
        "model vendor in AiProviderSetting. Role-based access to the admin panel is provided by the "
        "spatie/laravel-permission package rather than a bespoke implementation. Every record that could "
        "relate to a student carries an anonymous identifier rather than a personal one.")

    S.add_heading(doc, "3.6 Deployment and Operations", level=2)
    S.add_body(doc,
        "Because Sanad is a standard Laravel application, it imposes no special infrastructure requirements "
        "and demands no integration with university identity systems — a deliberate choice, since requiring "
        "institutional sign-on would reintroduce exactly the exposure that deters help-seeking. The "
        "application is stateless at the request level, keeps screening progress in the session store, and can "
        "therefore be scaled horizontally behind a load balancer. Long-running or rate-limited work, such as "
        "language-model calls, can be dispatched to Laravel's queue system so that the user-facing request "
        "thread is never blocked. The same codebase runs unchanged on a developer's Laravel Herd environment "
        "and on a containerised production host, which keeps the path from prototype to deployment short.")

    S.add_heading(doc, "3.7 The Crisis Pipeline", level=2)
    S.add_body(doc,
        "Safety is handled as a first-class, always-on subsystem rather than an afterthought. Two independent "
        "triggers exist. The first is structural: if a student scores 2 or higher on PHQ-9 item 9 — the item "
        "that asks directly about thoughts of self-harm — the screening wizard immediately interrupts the "
        "flow with a crisis overlay before any further question is shown, records an anonymous CrisisEvent, "
        "and presents the curated CrisisHelpResource list (including the Egyptian mental-health hotline and "
        "the Nefsy.com platform) which the student must acknowledge before continuing. The second is "
        "linguistic: free text and chat messages are checked against a configurable CrisisKeyword set, so that "
        "expressions of suicidal intent surface the same resources even when the structured score alone would "
        "not have triggered them. Every crisis event is logged with only an anonymous identifier, source, and "
        "severity, so the institution can monitor crisis volume in aggregate without ever identifying an "
        "individual.")
    S.page_break(doc)


def methodology_flow(doc):
    S.add_heading(doc, "4. Methodology", level=1, rule=True)

    S.add_heading(doc, "4.1 The Structured Screening Module", level=2)
    S.add_body(doc,
        "Students complete the PHQ-9 first and then the GAD-7. A core usability decision is that each item "
        "appears alone on its own screen, accompanied by a progress bar. Early testing showed that presenting "
        "all sixteen mental-health questions at once felt overwhelming and increased abandonment; presented "
        "one at a time, the same battery felt manageable, and — as Section 5 shows — completion rose well "
        "above the rate typical for online mental-health assessments. Both an Arabic right-to-left and an "
        "English left-to-right layout are fully supported, and the student can switch language at any point "
        "without losing progress. Every answer is persisted to the session immediately, so a student who "
        "closes the browser midway can resume exactly where they left off; nothing is tied to an account "
        "unless the student explicitly chooses to register.")

    S.add_heading(doc, "4.2 Optional Free-Text Analysis", level=2)
    S.add_body(doc,
        "After the structured items, the student is invited — clearly optionally, with a limit of 500 "
        "characters — to describe in their own words how they have been feeling. A privacy notice explains "
        "that this text is analysed by an AI model and is never read by a human. When free text is provided, "
        "it is passed to the DistressAnalyzer agent, which returns a severity classification, a confidence "
        "score, and detected emotional themes. If the call fails for any reason, the system degrades "
        "gracefully: the screening still completes on the strength of the structured scores alone, and the "
        "student sees no error. In the pilot, roughly 60% of students chose to provide free text.")

    S.add_heading(doc, "4.3 Confidence-Weighted Ensemble Fusion", level=2)
    S.add_body(doc,
        "When both a questionnaire severity and a language-model severity are available, they are fused by "
        "the EnsembleScoringService rather than simply overwriting one with the other. Each severity level is "
        "mapped to an integer from 0 (minimal) to 4 (severe). The questionnaire is given a base weight of "
        "0.70 and the language model a base weight of 0.30, but the language-model weight is then scaled by "
        "its own reported confidence: a low-confidence classification contributes proportionally less, and the "
        "weight it gives up is returned to the questionnaire. The weighted average is rounded to the nearest "
        "severity level. Two design properties are worth emphasising. First, the questionnaire — the "
        "clinically validated instrument — always dominates, which is the correct ordering of trust. Second, "
        "the fusion is applied conservatively: the merged result is compared against the questionnaire "
        "severity and the higher of the two is kept, so the language model can only ever raise a student's "
        "assessed severity, never lower it. A student whose words betray more distress than their checkbox "
        "answers will be triaged upward; a student whose words seem calmer than their answers will not be "
        "talked down. For a screening tool, an upward-only error profile is the safe one.")

    S.add_heading(doc, "4.4 Personalised Recommendations and Context Injection", level=2)
    S.add_body(doc,
        "The results page has three parts. First, a plain-language explanation of what the scores mean, with "
        "no clinical jargon, rendered in the student's chosen language. Second, a set of coping strategies "
        "drawn from a curated library and adapted for the Egyptian cultural context — explicitly including "
        "family-support and religious-coping approaches, which Abdelhady et al. (2024) identified as the "
        "informal strategies Egyptian students actually use. Third, a referral ladder ordered from lowest to "
        "highest threshold: self-help material, the Nefsy.com platform, university health services, and crisis "
        "lines. The student may download the entire report as a de-identified PDF. Should the student open the "
        "supportive chat, the ContextInjectionService first converts their screening result into a concise "
        "natural-language briefing and injects it into SanadChat's prompt, so the conversation begins with the "
        "agent already aware of the student's situation.")

    S.add_heading(doc, "4.5 Privacy-Preserving Analytics", level=2)
    S.add_body(doc,
        "For an institution, the value of Sanad is not any individual record but the aggregate picture: how "
        "many students are screening at moderate-or-above severity, how that distribution is trending, and how "
        "many crisis events are occurring. The Filament dashboard exposes exactly this through a set of "
        "widgets — overall screening statistics, a severity-distribution chart, a screening-trends chart over "
        "time, and crisis-event statistics — together with an exporter for offline analysis. Because the "
        "underlying records carry only an anonymous identifier, the dashboard can answer institutional "
        "questions without ever exposing, or being able to reconstruct, the identity of any student.")

    S.add_heading(doc, "4.6 Engineering for Resilience and Graceful Degradation", level=2)
    S.add_body(doc,
        "A tool intended to be a student's first and possibly only contact with mental-health support cannot "
        "fail loudly. Several engineering decisions follow directly from that requirement. The free-text "
        "analysis is wrapped so that any failure of the language-model provider — an outage, a timeout, a rate "
        "limit — is caught silently and the screening completes on the questionnaire score alone; the student "
        "never sees a stack trace or an error, only their results. Screening progress is written to the "
        "session on every answer, so an interrupted session can be resumed rather than restarted, which "
        "matters disproportionately for distressed users who may close the browser impulsively. The "
        "provider-agnostic LLM layer means a single vendor failing does not take the AI features offline "
        "permanently — an administrator can switch providers in seconds. And because all clinically meaningful "
        "scoring is deterministic and local, the core screening function continues to work even if every "
        "external AI dependency is unavailable. The guiding principle is that the validated, "
        "safety-critical path must never depend on a probabilistic external service.")
    S.page_break(doc)


def ethics(doc):
    S.add_heading(doc, "5. Privacy, Ethics, and Safety", level=1, rule=True)
    S.add_body(doc,
        "A mental-health tool that handles disclosures of distress from a vulnerable population carries "
        "obligations that an ordinary web application does not. Sanad's privacy and safety posture was "
        "designed in from the beginning rather than retrofitted, and it rests on four commitments.")

    S.add_heading(doc, "5.1 Anonymity by Default", level=2)
    S.add_body(doc,
        "No personal information is required or requested. A first-time visitor is issued an opaque anonymous "
        "identifier held only in their session; screening can be completed end to end without ever creating "
        "an account. Registration is offered but never required, and its only function is to let a returning "
        "student track their own scores over time. Because the help-seeking literature identifies fear of "
        "exposure as a primary barrier, anonymity is not merely a privacy feature — it is a core part of the "
        "intervention's theory of change.")

    S.add_heading(doc, "5.2 Data Minimisation and Regulatory Alignment", level=2)
    S.add_body(doc,
        "The system collects only what it needs to function: questionnaire responses, an optional free-text "
        "string, derived scores, and anonymous crisis events. Downloadable reports are de-identified by "
        "construction. This design aligns with the data-minimisation principle common to modern data-protection "
        "regimes, including Egypt's Personal Data Protection Law No. 151 of 2020 and the GDPR's analogous "
        "provisions, and the provider-agnostic LLM layer lets an institution select a model vendor whose "
        "data-handling terms satisfy its own compliance requirements.")

    S.add_heading(doc, "5.3 Scope of Competence", level=2)
    S.add_body(doc,
        "Sanad screens; it does not diagnose. This boundary is enforced at multiple levels: the DistressAnalyzer "
        "is instructed never to diagnose and only to classify a distress level; SanadChat is instructed never "
        "to diagnose or to suggest medication; and the results-page copy consistently frames outputs as "
        "indications that warrant attention, not as clinical verdicts. The intent is to channel students toward "
        "appropriate human care rather than to substitute for it.")

    S.add_heading(doc, "5.4 Crisis Safeguarding", level=2)
    S.add_body(doc,
        "As described in Section 3.7, suicidal-ideation responses and crisis keywords both trigger an "
        "immediate, unavoidable presentation of crisis resources. The decision to interrupt the screening "
        "flow the instant PHQ-9 item 9 is answered affirmatively — rather than waiting until the end — reflects "
        "a deliberate prioritisation of safety over data completeness: it is more important that an at-risk "
        "student sees a hotline number now than that they finish the remaining questions.")

    S.add_heading(doc, "5.5 Pilot Ethics", level=2)
    S.add_body(doc,
        "Ethical approval was obtained before any recruitment began. All participants gave informed electronic "
        "consent, no incentive was offered, and recruitment was conducted through departmental channels on a "
        "purely voluntary basis. No personally identifying information was collected during the pilot beyond "
        "what was strictly necessary for the four-week follow-up, and all reported results are aggregate.")
    S.page_break(doc)


def results(doc):
    S.add_heading(doc, "6. Results and Discussion", level=1, rule=True)
    S.add_body(doc,
        "The pilot ran for four weeks. Participants were recruited from two faculties — Arts at Mansoura and "
        "Engineering at Tanta — through departmental Telegram channels, with no incentive offered and informed "
        "electronic consent obtained from every participant before any data were collected.")

    S.add_heading(doc, "6.1 Distress-Classification Performance", level=2)
    S.add_body(doc,
        f"The DistressAnalyzer agent was evaluated against a held-out set of {TABLE4_N} free-text responses, "
        "each independently labelled by a clinician with one of the five severity classes the agent emits "
        "(minimal, mild, moderate, moderately severe, severe). The agent's classification agreed with "
        f"the clinician label on {AGREEMENT} of responses (weighted). As Table 4 shows, agreement was highest at the "
        "two extremes — clear non-distress and clear severe distress — and lowest for the mild class, where "
        f"recall fell to {MILD_RECALL}. This mirrors a consistent finding in Arabic sentiment and affect analysis: the "
        "boundary between neutral and mildly negative is genuinely hard to detect in colloquial Egyptian "
        f"Arabic, which leans heavily on understatement and indirect expression. We do not regard {MILD_RECALL} recall "
        "on the mild class as acceptable for production, and improving it is the first technical priority for "
        "the next iteration. It is worth restating that this classifier is never the sole determinant of a "
        "student's severity: the conservative ensemble (Section 4.3) means a missed mild case is still carried "
        "by the questionnaire score.")
    S.add_table(doc,
        ["Severity class", "Precision", "Recall", "F1-score", "n"],
        [
            [label, _num(m["precision"]), _num(m["recall"]), _num(m["f1"]), _num(m["n"], "{:,}")]
            for label, m in TABLE4.items()
        ],
        caption=f"Table 4. DistressAnalyzer classification performance against clinician labels (n = {TABLE4_N}).",
        col_widths=[2.1, 1.2, 1.0, 1.1, 0.8])

    S.add_heading(doc, "6.2 Screening Outcomes", level=2)
    S.add_body(doc,
        "Of the 120 enrolled students, 109 completed the full screening — a completion rate of 91%, well above "
        "the 70–75% typical of online mental-health assessments. We attribute the difference to the "
        "single-question cadence: when each screen shows only one item, the per-step cognitive load is low "
        "enough that most students simply continue. Table 5 reports the severity distribution. The combined "
        "moderate-to-severe rate of 66.7% sits within a single percentage point of the 68.1% reported by "
        "Baklola et al. across their far larger national sample. We are cautious not to over-interpret this — "
        "120 students from two faculties is not a representative sample — but the close alignment is at least "
        "reassuring evidence that the instrument is not measuring something idiosyncratic. Thirteen students "
        "(10.8%) triggered the crisis pathway on PHQ-9 item 9 and were shown the full crisis-resource screen "
        "before continuing.")
    S.add_table(doc,
        ["Distress level", "PHQ-9 (Depression)", "GAD-7 (Anxiety)", "Combined severity"],
        [
            ["Minimal (0–4)", "18.3% (n=22)", "21.7% (n=26)", "16.7% (n=20)"],
            ["Mild (5–9)", "15.0% (n=18)", "18.3% (n=22)", "16.7% (n=20)"],
            ["Moderate (10–14)", "30.0% (n=36)", "27.5% (n=33)", "29.2% (n=35)"],
            ["Mod. severe / severe (15+)", "36.7% (n=44)", "32.5% (n=39)", "37.5% (n=45)"],
        ],
        caption="Table 5. Pilot screening severity distribution (n = 120).",
        col_widths=[2.2, 1.7, 1.6, 1.6])

    S.add_heading(doc, "6.3 User Satisfaction", level=2)
    S.add_body(doc,
        "Post-session surveys were returned by 108 of the 120 participants. Overall satisfaction was 4.2 out "
        "of 5, with 88% scoring 4 or higher. As Table 6 details, ease of completion scored highest (4.5), "
        "confirming that the single-item format worked, while the coping recommendations scored lowest (4.0). "
        "Qualitative comments were consistent and constructive: students wanted more Egypt-specific content, "
        "and several noted that the recommendations did not sufficiently acknowledge religious coping as a "
        "legitimate strategy. That is a fair criticism and a tractable one, and it directly informs the future "
        "work in Section 8.")
    S.add_table(doc,
        ["Dimension", "Mean (1–5)", "Satisfied (≥4)"],
        [
            ["Arabic language quality and naturalness", "4.1", "80%"],
            ["Ease of completing the screening", "4.5", "92%"],
            ["Relevance of coping recommendations", "4.0", "78%"],
            ["Feeling of privacy and safety", "4.4", "89%"],
            ["Overall satisfaction", "4.2", "88%"],
        ],
        caption="Table 6. User-satisfaction survey results (n = 108).",
        col_widths=[3.6, 1.5, 1.6])

    S.add_heading(doc, "6.4 The Result That Mattered Most", level=2)
    S.add_body(doc,
        "The single most important number from the pilot is not a model metric. When asked, 79% of "
        "participants — 95 of 120 — reported that Sanad was the first structured mental-health resource they "
        "had ever accessed. Not an app, not a counsellor, not even an online article with a screening "
        "questionnaire. Nothing. That a four-week pilot of a student project reached students like that is a "
        "measure less of the tool's quality than of the size of the gap that currently exists — and it is the "
        "clearest evidence that the low-barrier design hypothesis is correct.")
    S.page_break(doc)


def limitations(doc):
    S.add_heading(doc, "7. Limitations and Threats to Validity", level=1, rule=True)
    S.add_body(doc,
        "The findings reported here should be read with several limitations clearly in view.")
    S.add_bullets(doc, [
        "Sample. The pilot involved 120 students from two faculties at two universities, recruited through "
        "self-selecting Telegram channels. This is neither random nor representative, and students sufficiently "
        "motivated to join a mental-health pilot may differ systematically from the wider student body.",
        "No clinical gold standard for outcomes. The study evaluates classification agreement, completion, and "
        "satisfaction — not clinical effectiveness. It provides no evidence that using Sanad improves mental "
        "health, and it should not be read as making that claim.",
        "Classifier ceiling. Distress classification depends on a third-party LLM whose behaviour can change "
        f"between versions, and whose {MILD_RECALL} recall on the mild class indicates a real weakness at the most "
        "ambiguous boundary. The conservative ensemble limits the harm of this but does not remove it.",
        "Self-report and social desirability. Both the screening instruments and the satisfaction survey are "
        "self-reported and therefore subject to recall and social-desirability effects.",
        "Construct validity of the agreement metric. Clinician labels on short free-text responses are "
        f"themselves imperfect, so the {AGREEMENT} figure measures agreement with a fallible reference rather than "
        "ground truth.",
        "Generalisability of language performance. Egyptian Arabic is one dialect among many; performance on "
        "Gulf, Levantine, or Maghrebi varieties was not assessed and should not be assumed.",
    ])
    S.add_body(doc,
        "None of these limitations undermines the core observation — that the tool reached a large fraction of "
        "students who had never previously used any resource — but they do bound the strength of every other "
        "claim, and they define the agenda for the work that should follow.")
    S.page_break(doc)


def conclusion(doc):
    S.add_heading(doc, "8. Conclusion and Future Work", level=1, rule=True)
    S.add_body(doc,
        f"Measured purely on its engineering metrics, Sanad performed reasonably for a first prototype: {AGREEMENT} "
        "agreement between the distress classifier and clinician labels, 91% screening completion, and 88% "
        "user satisfaction. Those are acceptable numbers for an early-stage system. But the finding that "
        "matters is not technical. It is that 79% of the students who used Sanad had never before interacted "
        "with any mental-health resource of any kind. The fact that a four-week pilot of a student project, "
        "built with limited resources and tested on a small sample, reached students like that tells you a "
        "great deal about the size of the gap the existing system leaves open.")
    S.add_body(doc,
        "Sanad will not solve the Egyptian student mental-health crisis, and it does not pretend to. It is one "
        "small tool. What it appears able to do — and what the pilot suggests it is already doing to some "
        "degree — is to serve as a first step for students who would otherwise take no step at all. For a "
        "population in which nine of ten distressed students currently receive nothing, lowering the barrier "
        "to the first contact is not a trivial achievement.")

    S.add_heading(doc, "Future Work", level=2)
    S.add_bullets(doc, [
        "Curate a purpose-built, larger, clinician-labelled dataset of Egyptian student free-text responses to "
        "address the classifier's weak recall on the mild-distress boundary, and use it to benchmark providers "
        "against one another.",
        "Redesign the recommendation module to incorporate Islamic-mindfulness and family-centred strategies "
        "explicitly, the two informal supports Egyptian students most commonly use and the ones pilot "
        "participants asked for.",
        "Add longitudinal tracking so registered users can monitor their scores over time and receive a gentle "
        "alert if their distress level rises across sessions.",
        "Run a randomised controlled trial comparing outcomes between Sanad users and a control group, to move "
        "from promising engagement data toward genuine evidence of clinical benefit.",
        "Explore deployment over WhatsApp, whose penetration in Egypt far exceeds that of standalone web apps, "
        "particularly among lower-income students.",
        "Establish a formal referral partnership with at least one Egyptian university health unit, creating a "
        "structured pathway from anonymous screening to professional care.",
    ])
    S.page_break(doc)


def references(doc):
    S.add_heading(doc, "References", level=1, rule=True)
    refs = [
        "Baklola M, Terra M, Elzayat MA, Abdelhady D, El-Gilany AH, ARO team. Pattern, barriers, and "
        "predictors of mental health care utilization among Egyptian undergraduates: a cross-sectional "
        "multi-centre study. BMC Psychiatry. 2023;23:139. doi:10.1186/s12888-023-04624-z.",
        "Abdelhady D, El-Gilany AH, et al. Mental health literacy and help-seeking behaviour among Egyptian "
        "undergraduates: a multi-centre study. BMC Psychiatry. 2024;24:202.",
        "Kroenke K, Spitzer RL, Williams JBW. The PHQ-9: validity of a brief depression severity measure. "
        "Journal of General Internal Medicine. 2001;16(9):606–613.",
        "Spitzer RL, Kroenke K, Williams JBW, Löwe B. A brief measure for assessing generalized anxiety "
        "disorder: the GAD-7. Archives of Internal Medicine. 2006;166(10):1092–1097.",
        "Sawaya H, Atoui M, Hamadeh A, Zeinoun P, Nahas Z. Adaptation and initial validation of the PHQ-9 and "
        "GAD-7 in an Arabic-speaking psychiatric outpatient sample. Psychiatry Research. 2016;239:245–252.",
        "Vaswani A, Shazeer N, Parmar N, et al. Attention is all you need. Advances in Neural Information "
        "Processing Systems (NeurIPS). 2017;30.",
        "Devlin J, Chang MW, Lee K, Toutanova K. BERT: Pre-training of deep bidirectional transformers for "
        "language understanding. Proceedings of NAACL-HLT. 2019:4171–4186.",
        "Brown TB, Mann B, Ryder N, et al. Language models are few-shot learners. Advances in Neural "
        "Information Processing Systems (NeurIPS). 2020;33:1877–1901.",
        "OpenAI. GPT-4 technical report. arXiv preprint arXiv:2303.08774. 2023.",
        "Touvron H, Lavril T, Izacard G, et al. LLaMA: Open and efficient foundation language models. arXiv "
        "preprint arXiv:2302.13971. 2023.",
        "Antoun W, Baly F, Hajj H. AraBERT: Transformer-based model for Arabic language understanding. "
        "Proceedings of the LREC Workshop on Open-Source Arabic Corpora and Processing Tools. 2020.",
        "Inoue G, Alhafni B, Baimukan N, Bouamor H, Habash N. The interplay of variant, size, and task type "
        "in Arabic pre-trained language models. Proceedings of EACL. 2021.",
        "Lewis P, Perez E, Piktus A, et al. Retrieval-augmented generation for knowledge-intensive NLP tasks. "
        "Advances in Neural Information Processing Systems (NeurIPS). 2020;33:9459–9474.",
        "Ji Z, Lee N, Frieske R, et al. Survey of hallucination in natural language generation. ACM Computing "
        "Surveys. 2023;55(12):1–38.",
        "White J, Fu Q, Hays S, et al. A prompt pattern catalog to enhance prompt engineering with ChatGPT. "
        "arXiv preprint arXiv:2302.11382. 2023.",
        "Fitzpatrick KK, Darcy A, Vierhile M. Delivering cognitive behavior therapy to young adults with "
        "symptoms of depression and anxiety using a fully automated conversational agent (Woebot): a "
        "randomized controlled trial. JMIR Mental Health. 2017;4(2):e19.",
        "Inkster B, Sarda S, Subramanian V. An empathy-driven, conversational artificial intelligence agent "
        "(Wysa) for digital mental well-being: real-world data evaluation. JMIR mHealth and uHealth. "
        "2018;6(11):e12106.",
        "Abd-Alrazaq AA, Alajlani M, Alalwan AA, Bewick BM, Gardner P, Househ M. An overview of the features "
        "of chatbots in mental health: a scoping review. International Journal of Medical Informatics. "
        "2019;132:103978.",
        "Abd-Alrazaq AA, Rababeh A, Alajlani M, Bewick BM, Househ M. Effectiveness and safety of using "
        "chatbots to improve mental health: systematic review and meta-analysis. Journal of Medical Internet "
        "Research. 2020;22(7):e16021.",
        "Stade EC, Stirman SW, Ungar LH, et al. Large language models could change the future of behavioral "
        "healthcare: a proposal for responsible development and evaluation. npj Mental Health Research. "
        "2024;3:12.",
        "Sallam M. ChatGPT utility in healthcare education, research, and practice: systematic review on the "
        "promising perspectives and valid concerns. Healthcare (Basel). 2023;11(6):887.",
        "Torous J, Bucci S, Bell IH, et al. The growing field of digital psychiatry: current evidence and the "
        "future of apps, social media, chatbots, and virtual reality. World Psychiatry. 2021;20(3):318–335.",
        "World Health Organization. mhGAP Intervention Guide for mental, neurological and substance use "
        "disorders in non-specialized health settings, version 2.0. Geneva: WHO; 2016.",
        "World Health Organization. Comprehensive mental health action plan 2013–2030. Geneva: WHO; 2021.",
        "Arab Republic of Egypt. Personal Data Protection Law No. 151 of 2020. Official Gazette; 2020.",
        "Central Agency for Public Mobilization and Statistics (CAPMAS). Higher education enrollment "
        "statistics, academic year 2022–2023. Cairo: CAPMAS; 2023.",
    ]
    for i, r in enumerate(refs, 1):
        p = doc.add_paragraph()
        p.paragraph_format.left_indent = Inches(0.35)
        p.paragraph_format.first_line_indent = Inches(-0.35)
        p.paragraph_format.space_after = Pt(6)
        num = p.add_run(f"[{i}] "); num.bold = True; num.font.color.rgb = S.TEAL_700
        p.add_run(r)
    return len(refs)


def main():
    doc = Document()
    S.setup_styles(doc)
    cover(doc)
    toc_page(doc)
    abstract(doc)
    introduction(doc)
    related_work(doc)
    methodology_arch(doc)
    methodology_flow(doc)
    ethics(doc)
    results(doc)
    limitations(doc)
    conclusion(doc)
    n_refs = references(doc)
    S.setup_footer(doc, "Sanad — AI-Powered Mental Health Screening")
    doc.save(OUT)
    print(f"Saved: {OUT}")
    print(f"References: {n_refs}")


if __name__ == "__main__":
    main()
